spring.application.name=Operaciones bancarias

server.port=8093
spring.data.mongodb.uri=mongodb+srv://zjulian1208:Abc1234@cluster0.de1kt.mongodb.net/sample_mflix?retryWrites=true&w=majority&appName=Cluster0

springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html