spring.application.name=Operaciones bancarias

server.port=8093
spring.data.mongodb.uri=mongodb+srv://zjulian1208:zjulian1208@clusteraws.dud8s.mongodb.net/bankReactivo?retryWrites=true&w=majority&appName=ClusterAWS

springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html