spring.application.name=Operaciones bancarias

server.port=8093
spring.data.mongodb.uri=mongodb+srv://daniR:abc123.@audit.ngzwq.mongodb.net/AuditBankingOperations?retryWrites=true&w=majority&appName=Audit

springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

#ActiveMQ
spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.username=admin
spring.activemq.password=admin
spring.activemq.packages.trust-all=true